Debug setup.outputs.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -59,76 +59,84 @@ jobs:
   setup:
     uses: ./.github/workflows/setup.yml
 
-  linux_build_and_test:
-    name: Linux
+  debug:
     needs: setup
-    if: >-
-      ${{
-        needs.setup.outputs.linux_amdgpu_families != '[]' &&
-        needs.setup.outputs.enable_build_jobs == 'true'
-      }}
-    strategy:
-      fail-fast: false
-      matrix:
-        families: ${{ fromJSON(needs.setup.outputs.linux_amdgpu_families) }}
-    uses: ./.github/workflows/ci_linux.yml
-    secrets: inherit
-    with:
-      amdgpu_families: ${{ matrix.families.family }}
-      test_runs_on: ${{ matrix.families.test-runs-on }}
-      artifact_run_id: ${{ inputs.artifact_run_id }}
-      expect_failure: ${{ matrix.families.expect_failure == true }}
-      use_prebuilt_artifacts: ${{ inputs.linux_use_prebuilt_artifacts == true && 'true' || 'false' }}
-      rocm_package_version: ${{ needs.setup.outputs.version }}
-    permissions:
-      contents: read
-      id-token: write
-
-  windows_build_and_test:
-    name: Windows
-    needs: setup
-    if: >-
-      ${{
-        needs.setup.outputs.windows_amdgpu_families != '[]' &&
-        needs.setup.outputs.enable_build_jobs == 'true'
-      }}
-    strategy:
-      fail-fast: false
-      matrix:
-        families: ${{ fromJSON(needs.setup.outputs.windows_amdgpu_families) }}
-    uses: ./.github/workflows/ci_windows.yml
-    with:
-      amdgpu_families: ${{ matrix.families.family }}
-      test_runs_on: ${{ matrix.families.test-runs-on }}
-      artifact_run_id: ${{ inputs.artifact_run_id }}
-      expect_failure: ${{ matrix.families.expect_failure == true }}
-      use_prebuilt_artifacts: ${{ inputs.windows_use_prebuilt_artifacts == true && 'true' || 'false' }}
-      rocm_package_version: ${{ needs.setup.outputs.version }}
-    permissions:
-      contents: read
-      id-token: write
-
-  # build_python_packages:
-  #   name: Build Python Packages
-  #   uses: ./.github/workflows/build_python_packages.yml
-
-  ci_summary:
-    name: CI Summary
-    if: always()
-    needs:
-      - setup
-      - linux_build_and_test
-      - windows_build_and_test
     runs-on: ubuntu-24.04
     steps:
-      - name: Output failed jobs
+      - name: Echo version from setup output
         run: |
-          echo '${{ toJson(needs) }}'
-          FAILED_JOBS="$(echo '${{ toJson(needs) }}' \
-            | jq --raw-output \
-            'map_values(select(.result!="success" and .result!="skipped")) | keys | join(",")' \
-          )"
-          if [[ "${FAILED_JOBS}" != "" ]]; then
-            echo "The following jobs failed: ${FAILED_JOBS}"
-            exit 1
-          fi
+          echo ${{ needs.setup.outputs.rocm_package_version }}
+
+  # linux_build_and_test:
+  #   name: Linux
+  #   needs: setup
+  #   if: >-
+  #     ${{
+  #       needs.setup.outputs.linux_amdgpu_families != '[]' &&
+  #       needs.setup.outputs.enable_build_jobs == 'true'
+  #     }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       families: ${{ fromJSON(needs.setup.outputs.linux_amdgpu_families) }}
+  #   uses: ./.github/workflows/ci_linux.yml
+  #   secrets: inherit
+  #   with:
+  #     amdgpu_families: ${{ matrix.families.family }}
+  #     test_runs_on: ${{ matrix.families.test-runs-on }}
+  #     artifact_run_id: ${{ inputs.artifact_run_id }}
+  #     expect_failure: ${{ matrix.families.expect_failure == true }}
+  #     use_prebuilt_artifacts: ${{ inputs.linux_use_prebuilt_artifacts == true && 'true' || 'false' }}
+  #     rocm_package_version: ${{ needs.setup.outputs.rocm_package_version }}
+  #   permissions:
+  #     contents: read
+  #     id-token: write
+
+  # windows_build_and_test:
+  #   name: Windows
+  #   needs: setup
+  #   if: >-
+  #     ${{
+  #       needs.setup.outputs.windows_amdgpu_families != '[]' &&
+  #       needs.setup.outputs.enable_build_jobs == 'true'
+  #     }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       families: ${{ fromJSON(needs.setup.outputs.windows_amdgpu_families) }}
+  #   uses: ./.github/workflows/ci_windows.yml
+  #   with:
+  #     amdgpu_families: ${{ matrix.families.family }}
+  #     test_runs_on: ${{ matrix.families.test-runs-on }}
+  #     artifact_run_id: ${{ inputs.artifact_run_id }}
+  #     expect_failure: ${{ matrix.families.expect_failure == true }}
+  #     use_prebuilt_artifacts: ${{ inputs.windows_use_prebuilt_artifacts == true && 'true' || 'false' }}
+  #     rocm_package_version: ${{ needs.setup.outputs.rocm_package_version }}
+  #   permissions:
+  #     contents: read
+  #     id-token: write
+
+  # # build_python_packages:
+  # #   name: Build Python Packages
+  # #   uses: ./.github/workflows/build_python_packages.yml
+
+  # ci_summary:
+  #   name: CI Summary
+  #   if: always()
+  #   needs:
+  #     - setup
+  #     - linux_build_and_test
+  #     - windows_build_and_test
+  #   runs-on: ubuntu-24.04
+  #   steps:
+  #     - name: Output failed jobs
+  #       run: |
+  #         echo '${{ toJson(needs) }}'
+  #         FAILED_JOBS="$(echo '${{ toJson(needs) }}' \
+  #           | jq --raw-output \
+  #           'map_values(select(.result!="success" and .result!="skipped")) | keys | join(",")' \
+  #         )"
+  #         if [[ "${FAILED_JOBS}" != "" ]]; then
+  #           echo "The following jobs failed: ${FAILED_JOBS}"
+  #           exit 1
+  #         fi
